services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: unificada_backend
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/firebase-credentials.json
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/corporate.pem
      - SSL_CERT_FILE=/etc/ssl/certs/corporate.pem
      - GRPC_DEFAULT_SSL_ROOTS_FILE_PATH=/etc/ssl/certs/corporate.pem
    volumes:
      - ./backend:/app
      - ./secrets/firebase-credentials.json:/app/secrets/firebase-credentials.json:ro
      - ./infra/certs/corporate.pem:/etc/ssl/certs/corporate.pem:ro
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: unificada_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
